name: Ejecutar pruebas de Python

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Configurar node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        
    - name: Descargar codigo
      uses: actions/checkout@v2

    - name: Configurar el entorno de Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Instalar pytest
      run: pip install pytest
      
    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip    

    - name: Ejecutar pruebas
      run: pytest ./tests/
      
      
